const a = {
    bizChatId: '-1',
    bizChatUserId: null,
    bizClientMsgId: null,
    content: {
        msg: {
            appmsg: {
                appid: 'wx299208e619de7026',
                sdkver: '0',
                title: '分享 亚马逊客服 的微博',
                des: '#日亚扫货季#今天起，跟日亚购物车做个了结...',
                action: 'view',
                type: '7',
                showtype: '0',
                content: '',
                url: '',
                lowurl: '',
                dataurl: '',
                lowdataurl: '',
                contentattr: '0',
                streamvideo: {
                    streamvideourl: '',
                    streamvideototaltime: '0',
                    streamvideotitle: '',
                    streamvideowording: '',
                    streamvideoweburl: '',
                    streamvideothumburl: '',
                    streamvideoaduxinfo: '',
                    streamvideopublishid: '',
                },
                appattach: {
                    totallen: '0',
                    attachid: '',
                    emoticonmd5: '',
                    fileext: '',
                },
                extinfo: 'sinaweibo://detail?mblogid=3968109796799773&luicode=10000359',
                androidsource: '2',
                thumburl: '',
                mediatagname: '',
                messageaction: '',
                messageext: '',
                emoticongift: {
                    packageflag: '0',
                    packageid: '',
                },
                emoticonshared: {
                    packageflag: '0',
                    packageid: '',
                },
                designershared: {
                    designeruin: '0',
                    designername: 'null',
                    designerrediretcturl: 'null',
                },
                emotionpageshared: {
                    tid: '0',
                    title: 'null',
                    desc: 'null',
                    iconUrl: 'null',
                    secondUrl: 'null',
                    pageType: '0',
                },
                webviewshared: {
                    shareUrlOriginal: '',
                    shareUrlOpen: '',
                    jsAppId: '',
                    publisherId: '',
                },
                template_id: '0',
            },
        },
    },
    createTime: '1461577920365',
    flag: '0',
    hasXml: ['reserved'],
    imgPath: 'THUMBNAIL_DIRPATH://th_7d037fa9a1ada4a3118320f7482c39dc',
    isSend: '1',
    isShowTimer: null,
    lvbuffer: '',
    msgId: '43119',
    msgSeq: null,
    msgSvrId: '5414805542374726304',
    reserved: {
        msg: {
            appmsg: {
                emoticonshared: '',
                webviewshared: '',
                dataurl: '',
                designershared: '',
                extinfo: 'sinaweibo://detail?mblogid=3968109796799773&luicode=10000359',
                appattach: '',
                streamvideo: {
                    streamvideourl: '',
                    streamvideoweburl: '',
                    streamvideotitle: '',
                    streamvideopublishid: '',
                    streamvideototaltime: '0',
                    streamvideothumburl: '',
                },
                emotionpageshared: {
                    desc: 'null',
                    secondUrl: 'null',
                    title: 'null',
                    pageType: '0',
                },
                type: '7',
                $sdkver: '0',
                androidsource: '2',
                $appid: 'wx299208e619de7026',
                emoticongift: '',
                mediatagname: '',
                thumburl: '',
                action: 'view',
                content: '',
                contentattr: '0',
                template_id: '0',
                lowurl: '',
                title: '分享 亚马逊客服 的微博',
                url: '',
                messageext: '',
                messageaction: '',
            },
        },
    },
    status: '2',
    talker: 'l******',
    talkerId: '203',
    transBrandWording: null,
    transContent: null,
    type: '49',
    url_icon: null,
};
