const a = {
    bizChatId: '-1',
    bizChatUserId: null,
    bizClientMsgId: '',
    content: {
        msg: {
            appmsg: {
                appid: '',
                sdkver: '0',
                title: '',
                des: '',
                username: '',
                action: 'view',
                type: '8',
                showtype: '0',
                content: '',
                url: '',
                lowurl: '',
                dataurl: '',
                lowdataurl: '',
                contentattr: '0',
                streamvideo: {
                    streamvideourl: '',
                    streamvideototaltime: '0',
                    streamvideotitle: '',
                    streamvideowording: '',
                    streamvideoweburl: '',
                    streamvideothumburl: '',
                    streamvideoaduxinfo: '',
                    streamvideopublishid: '',
                },
                canvasPageItem: {
                    canvasPageXml: '',
                },
                appattach: {
                    totallen: '75010',
                    attachid: '0:0:fdedf620ab863dc8fe3f9e4b55be0551',
                    cdnattachurl: '',
                    emoticonmd5: 'fdedf620ab863dc8fe3f9e4b55be0551',
                    aeskey: '',
                    fileext: '',
                    islargefilemsg: '0',
                },
                extinfo: '',
                androidsource: '1',
                thumburl: '',
                mediatagname: '',
                messageaction: '',
                messageext: '',
                emoticongift: {
                    packageflag: '0',
                    packageid: '',
                },
                emoticonshared: {
                    packageflag: '0',
                    packageid: '',
                },
                designershared: {
                    designeruin: '0',
                    designername: 'null',
                    designerrediretcturl: 'null',
                },
                emotionpageshared: {
                    tid: '0',
                    title: 'null',
                    desc: 'null',
                    iconUrl: 'null',
                    secondUrl: 'null',
                    pageType: '0',
                },
                webviewshared: {
                    shareUrlOriginal: '',
                    shareUrlOpen: '',
                    jsAppId: '',
                    publisherId: '',
                },
                template_id: '',
                md5: '',
                weappinfo: {
                    username: '',
                    appid: '',
                    appservicetype: '0',
                },
                statextstr: '',
                websearch: {
                    rec_category: '0',
                },
            },
            fromusername: 'q******',
            scene: '0',
            appinfo: {
                version: '1',
                appname: '',
            },
            commenturl: '',
        },
    },
    createTime: '1530283213000',
    flag: '0',
    hasXml: ['reserved'],
    imgPath: 'THUMBNAIL_DIRPATH://th_8c63c984d52d5f08e77e0ff6f1fd4911',
    isSend: '0',
    isShowTimer: null,
    lvbuffer: '$~BLOB~lvbuffer$',
    msgId: '27005',
    msgSeq: '680453174',
    msgSvrId: '4451357899004682985',
    reserved: {
        msg: {
            appmsg: {
                emoticonshared: '',
                dataurl: '',
                webviewshared: '',
                weappinfo: {
                    appservicetype: '0',
                    appid: '',
                    username: '',
                },
                md5: '',
                designershared: '',
                extinfo: '',
                streamvideo: {
                    streamvideourl: '',
                    streamvideoweburl: '',
                    streamvideotitle: '',
                    streamvideopublishid: '',
                    streamvideototaltime: '0',
                    streamvideothumburl: '',
                },
                appattach: '',
                emotionpageshared: {
                    desc: 'null',
                    secondUrl: 'null',
                    title: 'null',
                    pageType: '0',
                },
                type: '8',
                $sdkver: '0',
                websearch: '',
                androidsource: '1',
                $appid: '',
                emoticongift: '',
                mediatagname: '',
                thumburl: '',
                action: 'view',
                content: '',
                contentattr: '0',
                template_id: '',
                lowurl: '',
                title: '',
                canvasPageItem: '',
                url: '',
                messageext: '',
                statextstr: '',
                messageaction: '',
                username: '',
            },
            commenturl: '',
            appinfo: {
                appname: '',
                version: '1',
            },
            fromusername: 'q******',
            scene: '0',
        },
    },
    status: '3',
    talker: 'q******',
    talkerId: '125',
    transBrandWording: null,
    transContent: null,
    type: '1048625',
};
