const a = {
    bizChatId: '-1',
    bizChatUserId: null,
    bizClientMsgId: '',
    content: {
        msg: {
            appmsg: {
                appid: '',
                sdkver: '0',
                title: '',
                des: '',
                username: '',
                action: 'view',
                type: '8',
                showtype: '0',
                content: '',
                url: '',
                lowurl: '',
                dataurl: '',
                lowdataurl: '',
                contentattr: '0',
                streamvideo: {
                    streamvideourl: '',
                    streamvideototaltime: '0',
                    streamvideotitle: '',
                    streamvideowording: '',
                    streamvideoweburl: '',
                    streamvideothumburl: '',
                    streamvideoaduxinfo: '',
                    streamvideopublishid: '',
                },
                canvasPageItem: {
                    canvasPageXml: '',
                },
                appattach: {
                    totallen: '211791',
                    attachid: '0:0:cfd003cbaa38846dafe4bb0e0e0b084f',
                    cdnattachurl: '',
                    emoticonmd5: 'cfd003cbaa38846dafe4bb0e0e0b084f',
                    aeskey: '',
                    fileext: '',
                    islargefilemsg: '0',
                    cdnthumburl:
                        '3064020100045d305b02010002046ab170f302033d11fe02042bccf73a02045d1d76cf0436313435313539333539375f313636303633333636375f39653832616534303039383233343334653039326563306637386463353931380204010400030201000400',
                    cdnthumbaeskey: '71656279636f726b687179776b616677',
                    cdnthumblength: '13050',
                    cdnthumbwidth: '190',
                    cdnthumbheight: '190',
                    cdnthumbmd5: '9e82ae4009823434e092ec0f78dc5918',
                },
                extinfo: '',
                androidsource: '1',
                thumburl: '',
                mediatagname: '',
                messageaction: '',
                messageext: '',
                emoticongift: {
                    packageflag: '0',
                    packageid: '',
                },
                emoticonshared: {
                    packageflag: '0',
                    packageid: '',
                },
                designershared: {
                    designeruin: '0',
                    designername: 'null',
                    designerrediretcturl: 'null',
                },
                emotionpageshared: {
                    tid: '0',
                    title: 'null',
                    desc: 'null',
                    iconUrl: 'null',
                    secondUrl: 'null',
                    pageType: '0',
                },
                webviewshared: {
                    shareUrlOriginal: '',
                    shareUrlOpen: '',
                    jsAppId: '',
                    publisherId: '',
                },
                template_id: '',
                md5: '',
                weappinfo: {
                    username: '',
                    appid: '',
                    appservicetype: '0',
                    videopageinfo: {
                        thumbwidth: '0',
                        thumbheight: '0',
                        fromopensdk: '0',
                    },
                },
                statextstr: '',
                websearch: {
                    rec_category: '0',
                    channelId: '0',
                },
            },
            fromusername: 'q******',
            scene: '0',
            appinfo: {
                version: '1',
                appname: '',
            },
            commenturl: '',
        },
    },
    createTime: '1562253278000',
    flag: '0',
    hasXml: ['reserved'],
    imgPath: 'THUMBNAIL_DIRPATH://th_ae9b830eabe2c09d8e971ad90b690c2b',
    isSend: '0',
    isShowTimer: null,
    lvbuffer: '$~BLOB~lvbuffer$',
    msgId: '62710',
    msgSeq: '680531490',
    msgSvrId: '527644887678282837',
    reserved: {
        msg: {
            appmsg: {
                emoticonshared: '',
                webviewshared: '',
                dataurl: '',
                weappinfo: {
                    videopageinfo: {
                        thumbwidth: '0',
                        thumbheight: '0',
                    },
                    appservicetype: '0',
                    appid: '',
                    username: '',
                },
                md5: '',
                designershared: '',
                extinfo: '',
                appattach: '',
                streamvideo: {
                    streamvideourl: '',
                    streamvideoweburl: '',
                    streamvideotitle: '',
                    streamvideopublishid: '',
                    streamvideototaltime: '0',
                    streamvideothumburl: '',
                },
                emotionpageshared: {
                    desc: 'null',
                    secondUrl: 'null',
                    title: 'null',
                    pageType: '0',
                },
                type: '8',
                $sdkver: '0',
                websearch: '',
                androidsource: '1',
                $appid: '',
                emoticongift: '',
                mediatagname: '',
                thumburl: '',
                action: 'view',
                content: '',
                contentattr: '0',
                template_id: '',
                lowurl: '',
                title: '',
                canvasPageItem: '',
                url: '',
                statextstr: '',
                messageext: '',
                messageaction: '',
                username: '',
            },
            commenturl: '',
            appinfo: {
                appname: '',
                version: '1',
            },
            fromusername: 'q******',
            scene: '0',
        },
    },
    status: '3',
    talker: 'q******',
    talkerId: '125',
    transBrandWording: null,
    transContent: null,
    type: '1048625',
};
