module.exports = {
    baseDir: 'smileys',
    list: [
        {
            key: '/::)',
            alias: '微笑',
            file: '0.png',
            type: 'QQ经典',
        },
        {
            key: '/::~',
            alias: '撇嘴',
            file: '1.png',
            type: 'QQ经典',
        },
        {
            key: '/::B',
            alias: '色',
            file: '2.png',
            type: 'QQ经典',
        },
        {
            key: '/::|',
            alias: '发呆',
            file: '3.png',
            type: 'QQ经典',
        },
        {
            key: '/:8-)',
            alias: '得意',
            file: '4.png',
            type: 'QQ经典',
        },
        {
            key: '/::<',
            alias: '流泪',
            file: '5.png',
            type: 'QQ经典',
        },
        {
            key: '/::$',
            alias: '害羞',
            file: '6.png',
            type: 'QQ经典',
        },
        {
            key: '/::X',
            alias: '闭嘴',
            file: '7.png',
            type: 'QQ经典',
        },
        {
            key: '/::Z',
            alias: '睡',
            file: '8.png',
            type: 'QQ经典',
        },
        {
            key: "/::'(",
            alias: '大哭',
            file: '9.png',
            type: 'QQ经典',
        },
        {
            key: '/::-|',
            alias: '尴尬',
            file: '10.png',
            type: 'QQ经典',
        },
        {
            key: '/::@',
            alias: '发怒',
            file: '11.png',
            type: 'QQ经典',
        },
        {
            key: '/::P',
            alias: '调皮',
            file: '12.png',
            type: 'QQ经典',
        },
        {
            key: '/::D',
            alias: '呲牙',
            file: '13.png',
            type: 'QQ经典',
        },
        {
            key: '/::O',
            alias: '惊讶',
            file: '14.png',
            type: 'QQ经典',
        },
        {
            key: '/::(',
            alias: '难过',
            file: '15.png',
            type: 'QQ经典',
        },
        {
            key: '/::+',
            alias: '酷',
            file: '16.png',
            type: 'QQ经典',
        },
        {
            key: '/:--b',
            alias: '冷汗',
            file: '17.png',
            type: 'QQ经典',
        },
        {
            key: '/::Q',
            alias: '抓狂',
            file: '18.png',
            type: 'QQ经典',
        },
        {
            key: '/::T',
            alias: '吐',
            file: '19.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@P',
            alias: '偷笑',
            file: '20.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@-D',
            alias: '可爱',
            file: '21.png',
            type: 'QQ经典',
        },
        {
            key: '/::d',
            alias: '白眼',
            file: '22.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@o',
            alias: '傲慢',
            file: '23.png',
            type: 'QQ经典',
        },
        {
            key: '/::g',
            alias: '饥饿',
            file: '24.png',
            type: 'QQ经典',
        },
        {
            key: '/:|-)',
            alias: '困',
            file: '25.png',
            type: 'QQ经典',
        },
        {
            key: '/::!',
            alias: '惊恐',
            file: '26.png',
            type: 'QQ经典',
        },
        {
            key: '/::L',
            alias: '流汗',
            file: '27.png',
            type: 'QQ经典',
        },
        {
            key: '/::>',
            alias: '憨笑',
            file: '28.png',
            type: 'QQ经典',
        },
        {
            key: '/::,@',
            alias: '大兵',
            file: '29.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@f',
            alias: '奋斗',
            file: '30.png',
            type: 'QQ经典',
        },
        {
            key: '/::-S',
            alias: '咒骂',
            file: '31.png',
            type: 'QQ经典',
        },
        {
            key: '/:?',
            alias: '疑问',
            file: '32.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@x',
            alias: '嘘',
            file: '33.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@@',
            alias: '晕',
            file: '34.png',
            type: 'QQ经典',
        },
        {
            key: '/::8',
            alias: '折磨',
            file: '35.png',
            type: 'QQ经典',
        },
        {
            key: '/:,@!',
            alias: '衰',
            file: '36.png',
            type: 'QQ经典',
        },
        {
            key: '/:!!!',
            alias: '骷髅',
            file: '37.png',
            type: 'QQ经典',
        },
        {
            key: '/:xx',
            alias: '敲打',
            file: '38.png',
            type: 'QQ经典',
        },
        {
            key: '/:bye',
            alias: '再见',
            file: '39.png',
            type: 'QQ经典',
        },
        {
            key: '/:wipe',
            alias: '擦汗',
            file: '40.png',
            type: 'QQ经典',
        },
        {
            key: '/:dig',
            alias: '抠鼻',
            file: '41.png',
            type: 'QQ经典',
        },
        {
            key: '/:handclap',
            alias: '鼓掌',
            file: '42.png',
            type: 'QQ经典',
        },
        {
            key: '/:&-(',
            alias: '糗大了',
            file: '43.png',
            type: 'QQ经典',
        },
        {
            key: '/:B-)',
            alias: '坏笑',
            file: '44.png',
            type: 'QQ经典',
        },
        {
            key: '/:<@',
            alias: '左哼哼',
            file: '45.png',
            type: 'QQ经典',
        },
        {
            key: '/:@>',
            alias: '右哼哼',
            file: '46.png',
            type: 'QQ经典',
        },
        {
            key: '/::-O',
            alias: '哈欠',
            file: '47.png',
            type: 'QQ经典',
        },
        {
            key: '/:>-|',
            alias: '鄙视',
            file: '48.png',
            type: 'QQ经典',
        },
        {
            key: '/:P-(',
            alias: '委屈',
            file: '49.png',
            type: 'QQ经典',
        },
        {
            key: "/::'|",
            alias: '快哭了',
            file: '50.png',
            type: 'QQ经典',
        },
        {
            key: '/:X-)',
            alias: '阴险',
            file: '51.png',
            type: 'QQ经典',
        },
        {
            key: '/::*',
            alias: '亲亲',
            file: '52.png',
            type: 'QQ经典',
        },
        {
            key: '/:@x',
            alias: '吓',
            file: '53.png',
            type: 'QQ经典',
        },
        {
            key: '/:8*',
            alias: '可怜',
            file: '54.png',
            type: 'QQ经典',
        },
        {
            key: '/:pd',
            alias: '菜刀',
            file: '55.png',
            type: 'QQ经典',
        },
        {
            key: '/:<W>',
            alias: '西瓜',
            file: '56.png',
            type: 'QQ经典',
        },
        {
            key: '/:beer',
            alias: '啤酒',
            file: '57.png',
            type: 'QQ经典',
        },
        {
            key: '/:basketb',
            alias: '篮球',
            file: '58.png',
            type: 'QQ经典',
        },
        {
            key: '/:oo',
            alias: '乒乓',
            file: '59.png',
            type: 'QQ经典',
        },
        {
            key: '/:coffee',
            alias: '咖啡',
            file: '60.png',
            type: 'QQ经典',
        },
        {
            key: '/:eat',
            alias: '饭',
            file: '61.png',
            type: 'QQ经典',
        },
        {
            key: '/:pig',
            alias: '猪头',
            file: '62.png',
            type: 'QQ经典',
        },
        {
            key: '/:rose',
            alias: '玫瑰',
            file: '63.png',
            type: 'QQ经典',
        },
        {
            key: '/:fade',
            alias: '凋谢',
            file: '64.png',
            type: 'QQ经典',
        },
        {
            key: '/:showlove',
            alias: '嘴唇',
            file: '65.png',
            type: 'QQ经典',
        },
        {
            key: '/:heart',
            alias: '爱心',
            file: '66.png',
            type: 'QQ经典',
        },
        {
            key: '/:break',
            alias: '心碎',
            file: '67.png',
            type: 'QQ经典',
        },
        {
            key: '/:cake',
            alias: '蛋糕',
            file: '68.png',
            type: 'QQ经典',
        },
        {
            key: '/:li',
            alias: '闪电',
            file: '69.png',
            type: 'QQ经典',
        },
        {
            key: '/:bome',
            alias: '炸弹',
            file: '70.png',
            type: 'QQ经典',
        },
        {
            key: '/:kn',
            alias: '刀',
            file: '71.png',
            type: 'QQ经典',
        },
        {
            key: '/:footb',
            alias: '足球',
            file: '72.png',
            type: 'QQ经典',
        },
        {
            key: '/:ladybug',
            alias: '瓢虫',
            file: '73.png',
            type: 'QQ经典',
        },
        {
            key: '/:shit',
            alias: '便便',
            file: '74.png',
            type: 'QQ经典',
        },
        {
            key: '/:moon',
            alias: '月亮',
            file: '75.png',
            type: 'QQ经典',
        },
        {
            key: '/:sun',
            alias: '太阳',
            file: '76.png',
            type: 'QQ经典',
        },
        {
            key: '/:gift',
            alias: '礼物',
            file: '77.png',
            type: 'QQ经典',
        },
        {
            key: '/:hug',
            alias: '拥抱',
            file: '78.png',
            type: 'QQ经典',
        },
        {
            key: '/:strong',
            alias: '强',
            file: '79.png',
            type: 'QQ经典',
        },
        {
            key: '/:weak',
            alias: '弱',
            file: '80.png',
            type: 'QQ经典',
        },
        {
            key: '/:share',
            alias: '握手',
            file: '81.png',
            type: 'QQ经典',
        },
        {
            key: '/:v',
            alias: '胜利',
            file: '82.png',
            type: 'QQ经典',
        },
        {
            key: '/:@)',
            alias: '抱拳',
            file: '83.png',
            type: 'QQ经典',
        },
        {
            key: '/:jj',
            alias: '勾引',
            file: '84.png',
            type: 'QQ经典',
        },
        {
            key: '/:@@',
            alias: '拳头',
            file: '85.png',
            type: 'QQ经典',
        },
        {
            key: '/:bad',
            alias: '差劲',
            file: '86.png',
            type: 'QQ经典',
        },
        {
            key: '/:lvu',
            alias: '爱你',
            file: '87.png',
            type: 'QQ经典',
        },
        {
            key: '/:no',
            alias: 'NO',
            file: '88.png',
            type: 'QQ经典',
        },
        {
            key: ['/OK', '[OK]', '/:ok'],
            alias: 'OK',
            file: '89.png',
            type: 'QQ经典',
        },
        {
            key: '/:love',
            alias: '爱情',
            file: '90.png',
            type: 'QQ经典',
        },
        {
            key: '/:<L>',
            alias: '飞吻',
            file: '91.png',
            type: 'QQ经典',
        },
        {
            key: '/:jump',
            alias: '跳跳',
            file: '92.png',
            type: 'QQ经典',
        },
        {
            key: '/:shake',
            alias: '发抖',
            file: '93.png',
            type: 'QQ经典',
        },
        {
            key: '/:<O>',
            alias: '怄火',
            file: '94.png',
            type: 'QQ经典',
        },
        {
            key: '/:circle',
            alias: '转圈',
            file: '95.png',
            type: 'QQ经典',
        },
        {
            key: '/:kotow',
            alias: '磕头',
            file: '96.png',
            type: 'QQ经典',
        },
        {
            key: '/:turn',
            alias: '回头',
            file: '97.png',
            type: 'QQ经典',
        },
        {
            key: '/:skip',
            alias: '跳绳',
            file: '98.png',
            type: 'QQ经典',
        },
        {
            key: '/:oY',
            alias: '投降',
            file: '99.png',
            type: 'QQ经典',
        },
        {
            key: '/:#-0',
            alias: '激动',
            file: '100.png',
            type: 'QQ经典',
        },
        {
            key: '/:hiphot',
            alias: '街舞',
            file: '101.png',
            type: 'QQ经典',
        },
        {
            key: '/:kiss',
            alias: '献吻',
            file: '102.png',
            type: 'QQ经典',
        },
        {
            key: '/:<&',
            alias: '左太极',
            file: '103.png',
            type: 'QQ经典',
        },
        {
            key: '/:&>',
            alias: '右太极',
            file: '104.png',
            type: 'QQ经典',
        },
    ],
};
