module.exports = {
    baseDir: 'newemoji',
    list: [
        { type: '微信经典', alias: '奸笑', file: '2_02.png' },
        { type: '微信经典', alias: '嘿哈', file: '2_04.png' },
        { type: '微信经典', alias: '捂脸', file: '2_05.png' },
        { type: '微信经典', alias: '机智', file: '2_06.png' },
        { type: '微信经典', alias: '茶', file: '2_07.png' },
        { type: '微信经典', alias: '红包', file: '2_09.png' },
        { type: '微信经典', alias: '蜡烛', file: '2_10.png' },
        { type: '微信经典', alias: '耶', file: '2_11.png' },
        { type: '微信经典', alias: '皱眉', file: '2_12.png' },
        { type: '微信经典', alias: '囧', file: 'smiley_17b.png' },
        { type: '微信经典', alias: '抱拳', file: 'smiley_83b.png' },
        { type: '微信经典', alias: '鸡', file: '2_14.png' },
        { type: '微信经典', alias: '福', file: '2_15.png' },
        { type: '微信经典', alias: '再见', file: 'smiley_39b.png' },
        { type: '微信经典', alias: '發', file: '2_16.png' },
        { type: '微信经典', alias: '小狗', file: '2_17.png' },
        { type: '微信经典', alias: '吃瓜', file: 'Watermelon.png' },
        { type: '微信经典', alias: '加油', file: 'Addoil.png' },
        { type: '微信经典', alias: '汗', file: 'Sweat.png' },
        { type: '微信经典', alias: '天啊', file: 'Shocked!.png' },
        { type: '微信经典', alias: 'Emm', file: 'Cold.png' },
        { type: '微信经典', alias: '社会社会', file: 'Social.png' },
        { type: '微信经典', alias: '旺柴', file: 'Yellowdog.png' },
        { type: '微信经典', alias: '好的', file: 'NoProb.png' },
        { type: '微信经典', alias: '打脸', file: 'Slap.png' },
        { type: '微信经典', alias: '哇', file: 'Wow!.png' },
        { type: '微信经典', alias: '加油加油', file: 'KeepFighting.png' },
    ],
};
